on:
    workflow_dispatch:

jobs:
    deploy_the_site:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
              with:
                repository: JackMead/goal-tracker
                path: src
            - name: Checkout this repo
              uses: actions/checkout@v4
              with:
                path: dest
                ref: gh-pages
            - name: Build the prod version
              run: npm install && run build
              working-directory: src
            - name: Copy the build artefact into the destination folder
              run: cp -r src/build dest
            - name: Commit & push to this repo
              run: |
                git config user.name "deploy" && git config user.email "github@efactorypulse.com"
                git add .
                git commit -m "release"
                git push
                